
const formData = {
  application: "payment",
  type: "core",
  fields: [
    {
      name: "transaction_type",
      label: "Transaction Type",
      type: "select",
      multi: true,
      mandatory: true,
      max_multifield: 3,
      
    },
    {
      name: "debit_account",
      label: "Debit Account",
      type: "int",
      multi: false,
      mandatory: true,
    },
    {
      name: "credit_account",
      label: "Credit Account",
      type: "int",
      multi: false,
      mandatory: true,
    },
    {
      name: "debit_currency",
      label: "Debit Currency",
      type: "select",
      oppotions: [123,456],
      multi: false,
      mandatory: true,
    },
    {
      name: "credit_currency",
      label: "Credit Currency",
      type: "select",
      multi: false,
      mandatory: true,
    },
    {
      name: "debit_amount",
      label: "Debit Amount",
      type: "amount",
      multi: false,
      mandatory: true,
      min_length: 1,
      max_length: 1000000000,
    },
    {
      name: "debit_value_date",
      label: "Debit Value Date",
      type: "date",
      multi: false,
      mandatory: true,
    },
    {
      name: "payment_details",
      label: "Payment Details",
      type: "textarea",
      multi: false,
      mandatory: false,
      max_length: 200,
    },
    {
      name: "charge_account",
      label: "Charge Account",
      type: "account",
      multi: false,
      mandatory: false,
    },
    {
      name: "charge_code",
      label: "Charge Code",
      type: "select",
      multi: false,
      mandatory: false,
    },
    {
      name: "ordering_customer",
      label: "Ordering Customer",
      type: "string",
      multi: false,
      mandatory: true,
      min_length: 5,
      max_length: 100,
    },
    {
      name: "beneficiary",
      label: "Beneficiary",
      type: "string",
      multi: false, 
      mandatory: true,
      min_length: 5,
      max_length: 100,
    },
    {
      name: "beneficiary_address",
      label: "Beneficiary Address",
      type: "textarea",
      multi: false,
      mandatory: false,
      max_length: 150,
    },
    {
      name: "beneficiary_bank",
      label: "Beneficiary Bank",
      type: "string",
      multi: false,
      mandatory: false,
      min_length: 5,
      max_length: 100,
    },
    {
      name: "intermediary_bank",
      label: "Intermediary Bank",
      type: "string",
      multi: false,
      mandatory: false,
    },
    {
      name: "customer_reference",
      label: "Customer Reference",
      type: "reference",
      multi: false,
      mandatory: true,
    },
    {
      name: "internal_reference",
      label: "Internal Reference",
      type: "reference",
      multi: false,
      mandatory: false,
    },
    {
      name: "exchange_rate",
      label: "Exchange Rate",
      type: "number",
      multi: false,
      mandatory: false,
    },
    {
      name: "commission",
      label: "Commission",
      type: "amount",
      multi: false,
      mandatory: false,
    },
    {
      name: "tax",
      label: "Tax",
      type: "amount",
      multi: false,
      mandatory: false,
    },
    {
      name: "transaction_charges",
      label: "Transaction Charges",
      type: "amount",
      multi: false,
      mandatory: false,
    },
    {
      name: "narrative",
      label: "Narrative",
      type: "textarea",
      multi: false,
      mandatory: false,
      max_length: 250,
    },
    {
      name: "email_notification",
      label: "Email",
      type: "email",
      multi: false,
      mandatory: false,
    },
    {
      name: "sms_notification",
      label: "SMS Notification",
      type: "tel",
      multi: true,
      mandatory: false,
    },
    {
      name: "address",
      label: "Address",
      type: "string",
      multi: true,
      mandatory: true,
    },
    {
      name: "attachment",
      label: "Attachment",
      type: "file",
      multi: false,
      mandatory: false,
    },
    {
      name: "priority",
      label: "Priority",
      type: "select",
      multi: false,
      mandatory: true,
    },
    {
      name: "delivery_channel",
      label: "Delivery Channel",
      type: "select",
      multi: false,
      mandatory: true,
    },
  ],
};

export default formData;
