const customerRecordData = [
  {
    
    application: "customer",
    type: "core",
    record: {
        id: "CUST00123",
      customer_name_1: "John Smith",
      customer_name_2: "Mr.",
      short_name: "J Smith",
      category: "INDIVIDUAL",
      residency: "RESIDENT",
      nationality: "BANGLADESHI",
      legal_form: "INDIVIDUAL",
      date_birth_or_incorporation: "1980-05-15",
      id_type: "PASSPORT",
      id_number: "BD12345678",
      id_issue_date: "2018-06-10",
      id_expiry_date: "2028-06-09",
      industry_sector: "IT",
      employer_name: "Tech Solutions Ltd",
      customer_status: "ACTIVE",
      risk_rating: "LOW",
      pep: "NO",
      kyc_review_date: "2024-01-10",
      address_line_1: "123 Park Street",
      address_line_2: "Apt 5B",
      town_city: "Dhaka",
      country: "BANGLADESH",
      postal_code: "1205",
      mobile_phone: "+88801712345678",
      home_phone: "+88202345678",
      email_address: "john.smith@email.com",
      communication_preference: "EMAIL",
      relationship_officer: "RM001",
      notes: "High-value customer. Preferred for investment products."
    }
  },
  {
    
    application: "customer",
    type: "core",
    record: {
        id: "CUST00456",
      customer_name_1: "Alice Rahman",
      customer_name_2: "Mrs.",
      short_name: "A Rahman",
      category: "INDIVIDUAL",
      residency: "RESIDENT",
      nationality: "BANGLADESHI",
      legal_form: "INDIVIDUAL",
      date_birth_or_incorporation: "1985-03-22",
      id_type: "NATIONAL_ID",
      id_number: "4567890123456",
      id_issue_date: "2015-04-20",
      id_expiry_date: "2025-04-19",
      industry_sector: "HEALTHCARE",
      employer_name: "City Hospital",
      customer_status: "ACTIVE",
      risk_rating: "MEDIUM",
      pep: "NO",
      kyc_review_date: "2023-11-15",
      address_line_1: "456 Hospital Road",
      address_line_2: "",
      town_city: "Chittagong",
      country: "BANGLADESH",
      postal_code: "4000",
      mobile_phone: "+88801887654321",
      home_phone: "+88131234567",
      email_address: "alice.rahman@email.com",
      communication_preference: "SMS",
      relationship_officer: "RM002",
      notes: "Regular customer. Transfers funds quarterly."
    }
  },
  {
    
    application: "customer",
    type: "core",
    record: {
        id: "CUST00789",
      customer_name_1: "Global Enterprises Ltd",
      customer_name_2: "Company",
      short_name: "Global Ent",
      category: "CORPORATE",
      residency: "RESIDENT",
      nationality: "BANGLADESHI",
      legal_form: "PRIVATE_LIMITED",
      date_birth_or_incorporation: "2010-01-15",
      id_type: "BUSINESS_REGISTRATION",
      id_number: "BRN2010001234",
      id_issue_date: "2010-02-01",
      id_expiry_date: "2026-01-31",
      industry_sector: "MANUFACTURING",
      employer_name: "Global Enterprises Ltd",
      customer_status: "ACTIVE",
      risk_rating: "LOW",
      pep: "NO",
      kyc_review_date: "2024-03-20",
      address_line_1: "Industrial Area Block-5",
      address_line_2: "Plot 123",
      town_city: "Gazipur",
      country: "BANGLADESH",
      postal_code: "1700",
      mobile_phone: "+88809999999",
      home_phone: "+88196666666",
      email_address: "contact@globalent.com",
      communication_preference: "EMAIL",
      relationship_officer: "RM003",
      notes: "Major corporate client. High-volume transactions. Annual review completed."
    }
  }
];

export default customerRecordData;
